name: Update Mkdocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  create_mkdocs:
    strategy:
        matrix:
          python-version: [3.11]

    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v4
    -   name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
    -   name: Configure Git Credentials
        run: |
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
    -   uses: actions/cache@v4
        with:
            key: mkdocs-material-${{ env.cache_id }}
            path: .cache
            restore-keys: |
                mkdocs-material-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install mkdocs
        pip install mkdocs-material
        pip install mkdocstrings
        pip install git+https://github.com/timvink/mkdocs-table-reader-plugin.git
        pip install git+https://github.com/timvink/mkdocs-git-authors-plugin.git
        pip install mkdocstrings-python

        poetry install
    - run: mkdocs gh-deploy --force  
