name: Ruff Rules Check

on:

    pull_request:
        branches:
            - main

jobs:
    ruff-check:
        runs-on: ubuntu-latest

        strategy:
            matrix:
              python-version: [3.11]

        steps:
        -   name: Checkout code
            uses: actions/checkout@v2

        -   name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}

        -   name: Set up Node.js
            uses: actions/setup-node@v2
            with:
                node-version: 14

        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install

        -   name: Run Ruff rules check
            run: poetry run ruff check
