name: Ruff Rules Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    ruff-check:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v2

        -   name: Set up Node.js
            uses: actions/setup-node@v2
            with:
                node-version: 14

        -   name: Install dependencies
            run: npm install

        -   name: Run Ruff rules check
            run: npm run ruff-check
